FROM python:3

WORKDIR /usr/app/src

COPY requirements.txt ./

RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt

COPY . . 

ENV GOOGLE_APPLICATION_CREDENTIALS=/usr/app/src/credentials/twitter-pipeline-gcp-account.json

CMD [ "python",  "./twitter_consumer.py"]
