twitter_dbt:
  target: prod
  outputs:

    prod:
      type: bigquery
      method: service-account
      project: twitter-pipeline-352822
      dataset: twitter
      threads: 4
      keyfile: /usr/app/src/secrets/twitter-pipeline-big-query-user.json
      timeout_seconds: 300
      priority: interactive
      retries: 1